name: Run Build & Unit Tests
on:
  pull_request:
jobs:
  build:
    name: Build and test
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package.yml@feat-remove-npm-test-action'
    with:
      run_tests: true
