name: E2E Tests
on:
  push:
    branches:
      - main
      - maintenance
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      node-red:
        image: nodered/node-red:latest
        options: >
          --entrypoint "/bin/sh" -c "echo 123 && /usr/src/node-red/entrypoint.sh"
        volumes:
          - ./cypress/fixtures/user-dir/:/data
        ports:
          - 1881:1880
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Install Node-RED Dependencies
        working-directory: ./cypress/fixtures/user-dir/
        run: npm install
      - name: Run Linting Tests
        run: npm run lint
      - name: Run Dashboard E2E (Cypress) Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          config-file: cypress.config.js
          build: npm run build
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-output
          path: |
            cypress/screenshots
            cypress/videos